const createad = {
  newAd: "New Ad",
  chooseCategory: "Choose category",
  category: "Category",
  dealType: "Deal type",
  chooseDealType: "Choose deal type",
  salesman: "Salesman",
  chooseSalesman: "Choose salesman",
  titleAndDescription: "Title and Description",
  title: "Title",
  addTitle: "Add title",
  description: "Description",
  enterDescription: "Enter description",
  language: "Language",
  photoAndVideo: "Photo and video",
  coverPhotoInstructions: "The first photo will be on the cover of the ad.",
  dragToReorderPhotos: "Drag to reorder photos.",
  dragImageOrOpenExplorer: "Drag the image or <span>Open explorer</span>",
  photoSizeRecommendation:
    "1600x1200 or higher is recommended. <br> Max. 10 MB each (20 MB for video)",
  detailedInformation: "Detailed information",
  location: "Location",
  region: "Region",
  selectRegion: "Select region",
  province: "Province",
  selectProvince: "Select province",
  district: "District",
  selectDistrict: "Select district",
  subDistrict: "Sub District",
  selectSubDistrict: "Select Sub District",
  address: "Address",
  contacts: "Contacts",
  phone: "Phone",
  email: "Email",
  enterEmail: "Enter email",
  receiveMessagesDisclaimer:
    "If you want to receive messages from users (your email will be visible to the sender only if the question is answered)",
  postAdAgreement: `By clicking «Post Ad» you accept the <0>License Agreement</0> and agree to the <1>Privacy Policy</1>`,
  postAd: "Post Ad",
  edit: "Edit",
  congratulations: "Congratulations!",
  successfullyChangedAd: "You have successfully changed your ad",
};

export { createad };
