const errors = {
  mapErrorNoThailand: "Please select a location within Thailand",
  enterName: "Enter name",
  enterPhoneNumber: "Enter phone number",
  wrongPhoneNumberFormat: "Wrong phone number format",
  enterCompany: "Enter company",
  enterEmail: "Enter email",
  wrongEmailFormat: "Wrong email format",
  enterMessage: "Enter message",
  enterCode: "Enter code",
  wrongCode: "Wrong code",
  enterTitle: "Enter title",
  enterPrice: "Enter price",
  enterDescription: "Enter description",
  selectedOption: "Selected option",
  wrongPhoneOrEmailFormat: "Wrong phone/email format",
  enterFirstName: "Enter first name",
  enterLastName: "Enter last name",
  enterTheme: "Enter theme",
  selectedFile: "Selected file",
  invalidLinkFormat: "Invalid link format",
  linkIsRequired: "Link is required",
  fileTooBig1MB: "The file is too big. Drag a file smaller than 1 MB.",
  cannotAddMoreThan6Files: "You cannot add more than 6 files.",
  fileTooBig20MB: "The file is too big. Drag a file smaller than 20 MB.",
  fileTooBig10MB: "The file is too big. Drag a file smaller than 10 MB.",
  enterPassword: "Enter password",
  addressNotFound: "Address not found",
  selectNoMoreThan10Files: "You can select no more than 10 files.",
  fileTooBig: "The file is too big.",
  pageNotFound: "Oops!! Page Not Found",
  pageNotFoundMessage:
    "The page you're looking for is nowhere to be found. Don't worry, though; we can help you get back on track.",
  backToHome: "Back to Home",
};

export { errors };
