const general = {
  headerDescription: "Service of Private Advertisements",
  help: "Help",
  advertiseWithUs: "Advertise with us",
  rules: "Rules",
  wishTitle: "My Whishlist",
  createButton: "Create an Ad",
  viewAll: "View all",
  cancel: "Cancel",
  back: "Back",
  send: "Send",
  hide: "Hide",
  logIn: "Log In",
  donthaveAccount: "You don't have an account yet?",
  haveAccount: "Do you already have an account?",
  signUp: "Sign Up",
  phone: "Phone",
  password: "Password",
  forgotPassword: "Forgot password",
  termsOfUse: "Terms of Use",
  withTermsOfUse: "Terms of Use",
  loginAgree: "By Log In, you agree to our",
  orLogin: "Or Log In with",
  loginDescription:
    "If you want to receive messages from users (your email will be visible to the sender only if the question is answered)",
  specifiedNumberWillReceiveSMS:
    "The specified number will receive an SMS for authorization",
  bySignUpAgreement: "By Sign Up, you agree to our",
  associatedWithEmailOrPhoneNumber:
    "What email or phone number is associated with your BBGO profile?",
  enterPhoneOrEmail: "Enter phone or email",
  changePassword: "Change password",
  confirmNumber: "Confirm number",
  enterCodeSentTo: "Enter the code sent to",
  sendCodeAgain: "Send code again",
  notificationsMustBeEnabled: "Notifications must be enabled",
  anotherWayToGetCode: "Another way to get a code",
  receiveCodeWithin1to2Minutes:
    "Within 1-2 minutes you will receive a message with a code to verify your phone number",
  continue: "Continue",
  profile: "Profile",
  createAccount: "Create an account",
  firstName: "First name",
  lastName: "Last name",
  email: "Email",
  receiveBBGONewsAndPromotions:
    "Receive information about BBGO news and promotions",
  bbgoExclusiveOffersAndNotifications:
    "BBGO will send you exclusive offers, ideas, promotional emails and push notifications. You can opt out in your account settings or in a marketing notice.",
  home: "Home",
  select: "Select",
  reset: "Reset",
  showOnMap: "Show on Map",
  viewMore: "View more",
  default: "Default",
  showMore: "Show more",
  addNew: "Add New",
  updated: "Updated",
  ago: "ago",
  years: "years",
  year: "year",
  months: "months",
  month: "month",
  days: "days",
  day: "day",
  hours: "hours",
  hour: "hour",
  minutes: "minutes",
  minute: "minute",
  seconds: "seconds",
  second: "second",
  edit: "Edit",
  delete: "Delete",
  create: "Create",
  done: "Done",
  search: "Search",
  from: "From",
  online: "Online",
  more: "More",
  less: "Less",
  shareWith: "Share with",
  message: "Message",
  messageSent: "Your message has been sent",
  myMessages: "My messages",
  save: "Save",
  deleteAccount: "Delete account",
  logOut: "Log out",
  selected: "Selected",
  selectAll: "Select all",
  yourAdvertisement: "Your advertisement",
  addYourBanners: "Add your banners",
  add: "Add",
  deactivate: "Deactivate",
  active: "Active",
  view: "View",
  ad: "ad",
  activate: "Activate",
  empty: "Empty",
  subscribe: "Subscribe",
};

export { general };
