const profile = {
  profile: "Profile",
  accountSettings: "Account settings",
  myAds: "My ads",
  myMessages: "My messages",
  wallet: "Wallet",
  reviews: "Reviews",
  reviewedProducts: "Reviewed products",
  notifications: "Notifications",
  settings: "Settings",
  personalInfo: "Personal info",
  address: "Address",
  security: "Security",
  firstName: "First Name",
  lastName: "Last Name",
  emailAddress: "Email address",
  phone: "Phone",
  country: "Country",
  cityState: "City/State",
  password: "Password",
  enterPassword: "Enter Password",
  newPassword: "New Password",
  confirmPassword: "Confirm Password",
  confirmDeleteAccount: "Are you sure you want to delete your account?",
  confirmLogOut: "Are you sure you want to log out of your account?",
  myAdsSecond: "My Ads",
  active: "Active",
  waiting: "Waiting",
  inactive: "Inactive",
  rejected: "Rejected",
  selectAllAds:
    "Select all the desired ads from the list to apply the same actions to them",

  subscribeToNotifications: "Subscribe to notifications",
  receiveMessages: "If you want to receive messages from users, subscribe",
  areYouSure: "Are you sure you want to",
  deactivate: "deactivate",
  delete: "delete",
  ads: "ads",
  confirmActivateAd: "Are you sure you want to activate ad?",
  adsRejectedAfterModeration:
    "Ads rejected after moderation are displayed here.",
  editAndActivate:
    "Depending on why the ad was rejected, you can still edit it and try to activate it again.",
  banners: "Banners",
  uploadBanner: "Upload banner",
  dragImageOrOpenExplorer: "Drag the image or <span>Open explorer</span>",
  sizeAndFileType: "Size <100KB and file type PNG/GIF/JPEG",
  languageBanner: "Language banner",
  addLink: "Add link",
  yourBanners: "Your banners",
  fileName: "File nameи",
  size: "Size",
  dataUploaded: "Data uploaded",
  status: "Status",
  action: "Action",
  approved: "Approved",
  chooseAll: "Choose all",
  choosed: "Choosed",
  buy: "Buy",
  sell: "Sell",
  newMessages: "New Messages",
  allMessages: "All Messages",
  selectMessage: "Select a message to read it",
  confirmBlock: "Are you sure you want to block the user?",
  block: "Block",
  deleteChat: "Delete Chat",
  deleteChatWith: "Do you want to delete the chat with",
  goToAd: "Go to Ad",
  you: "You",
  noCardAdded: "You don't have a card added yet",
  addCardPrompt: "Add a card to be able to use paid services BBGO",
  addCard: "Add card",
  mainCard: "Main card",
  makeMainCard: "To make it the main one",
  removeCardWarning:
    "The card will be removed from your wallet and personal account",
  deleteCard: "Delete Card",
  successful: "Successful!",
  cardSuccessfullyAdded: "The card has been successfully added",
  cardNumber: "Card number",
  cvv: "CVV",
  validity: "Validity",
  mmYY: "MM/YY",
  bad: "Bad",
  badReviews: "This author has received many bad reviews",
  acceptable: "Acceptable",
  acceptableReviews: "This author has received many acceptable reviews",
  normal: "Normal",
  normalReviews: "This author has received many normal reviews",
  good: "Good",
  goodReviews: "This author has received many good reviews",
  excellent: "Excellent",
  excellentReviews: "This author has received many excellent reviews",
  yourReviews: "Your reviews",
  confirmDeleteReviewedProducts:
    "Are you sure you want to delete reviewed products?",
};

export { profile };
