import avatar from "images/main/avatar.png";
import cover1 from "images/main/card-product-real-estate.png";
import images1 from "images/profile/messages-1.png";
import images2 from "images/profile/messages-2.png";

export const chatLists = [
  {
    id: 0,
    name: "Viktor",
    avatar: avatar.src,
    title:
      "Country house in the forest from a wooden frame, in a picturesque place",
    cover: cover1.src,
    link: "/",
    statusOnline: false,
    timeOnline: "2:58 P.M",
    dateOnline: "02.09.2023",
    isNew: 2,
    messages: [
      {
        userIsSender: true,
        text: "I'm also curious about the pricing for these banner ads",
        time: "11:28 AM",
        date: "02.09.2023",
        images: [images1.src, images2.src],
      },
      {
        userIsSender: true,
        text: "I have a moderate budget, and I'm looking to run the campaign for one month. 🤔",
        time: "11:30 AM",
        date: "02.09.2023",
      },
      {
        userIsSender: false,
        text: "Great! 👍",
        time: "12:38 PM",
        date: "02.09.2023",
        images: [images1.src, images2.src, images1.src],
      },
      {
        userIsSender: false,
        text: "We have budget-friendly packages for one-month campaigns. To give you a more precise quote, could you share your target audience and any specific demographics you'd like to reach? ",
        time: "02:18 PM",
        date: "02.09.2023",
      },
      {
        userIsSender: true,
        text: "I'm also curious about the pricing for these banner ads",
        time: "11:28 AM",
        date: "02.09.2023",
      },
      {
        userIsSender: true,
        text: "I have a moderate budget, and I'm looking to run the campaign for one month. 🤔",
        time: "11:30 AM",
        date: "02.09.2023",
      },
      {
        userIsSender: false,
        text: "Great! 👍",
        time: "12:38 PM",
        date: "02.09.2023",
      },
      {
        userIsSender: false,
        text: "We have budget-friendly packages for one-month campaigns. To give you a more precise quote, could you share your target audience and any specific demographics you'd like to reach? ",
        time: "02:18 PM",
        date: "02.09.2023",
      },
    ],
  },
  {
    id: 1,
    name: "Vincent Gilmor",
    avatar: avatar.src,
    title: "Parking place for sale in a new underground parking",
    cover: cover1.src,
    link: "/",
    statusOnline: false,
    timeOnline: "2:58 P.M",
    dateOnline: "01.09.2023",
    messages: [
      {
        userIsSender: true,
        text: "I'm also curious about the pricing for these banner ads",
        time: "11:28 AM",
        date: "02.09.2023",
      },
      {
        userIsSender: true,
        text: "I have a moderate budget, and I'm looking to run the campaign for one month. 🤔",
        time: "11:30 AM",
        date: "02.09.2023",
        images: [images1.src, images2.src],
      },
      {
        userIsSender: false,
        text: "Great! 👍",
        time: "12:38 PM",
        date: "02.09.2023",
      },
      {
        userIsSender: false,
        text: "We have budget-friendly packages for one-month campaigns. To give you a more precise quote, could you share your target audience and any specific demographics you'd like to reach? ",
        time: "02:18 PM",
        date: "02.09.2023",
      },
    ],
  },
  {
    id: 2,
    name: "Karin Suchinda",
    avatar: avatar.src,
    title: "Luxurious apartment on the 5th floor",
    cover: cover1.src,
    link: "/",
    statusOnline: false,
    timeOnline: "2:58 P.M",
    dateOnline: "01.09.2023",
    messages: [
      {
        userIsSender: true,
        text: "If you need more options, then tell us we have a lot of offers",
        time: "11:28 AM",
        date: "12.06.2023",
      },
      {
        userIsSender: true,
        text: "It is also possible to meet on site at our office and discuss. 😉",
        time: "11:30 AM",
        date: "12.06.2023",
      },
      {
        userIsSender: false,
        text: "Great! 👍",
        time: "12:38 PM",
        date: "12.06.2023",
      },
      {
        userIsSender: false,
        // text: "We have budget-friendly packages for one-month campaigns. To give you a more precise quote, could you share your target audience and any specific demographics you'd like to reach? ",
        time: "02:18 PM",
        date: "12.06.2023",
        images: [images1.src],
      },
    ],
  },
];
export const sellChatList = [
  {
    id: 0,
    name: "Sell chat List",
    avatar: avatar.src,
    title:
      "Country house in the forest from a wooden frame, in a picturesque place",
    cover: cover1.src,
    link: "/",
    statusOnline: false,
    timeOnline: "2:58 P.M",
    dateOnline: "02.09.2023",
    isNew: 2,
    messages: [
      {
        userIsSender: true,
        text: "I'm also curious about the pricing for these banner ads",
        time: "11:28 AM",
        date: "02.09.2023",
      },
      {
        userIsSender: true,
        text: "I have a moderate budget, and I'm looking to run the campaign for one month. 🤔",
        time: "11:30 AM",
        date: "02.09.2023",
      },
      {
        userIsSender: false,
        text: "Great! 👍",
        time: "12:38 PM",
        date: "02.09.2023",
      },
      {
        userIsSender: false,
        text: "We have budget-friendly packages for one-month campaigns. To give you a more precise quote, could you share your target audience and any specific demographics you'd like to reach? ",
        time: "02:18 PM",
        date: "02.09.2023",
      },
      {
        userIsSender: true,
        text: "I'm also curious about the pricing for these banner ads",
        time: "11:28 AM",
        date: "02.09.2023",
      },
      {
        userIsSender: true,
        text: "I have a moderate budget, and I'm looking to run the campaign for one month. 🤔",
        time: "11:30 AM",
        date: "02.09.2023",
      },
      {
        userIsSender: false,
        text: "Great! 👍",
        time: "12:38 PM",
        date: "02.09.2023",
      },
      {
        userIsSender: false,
        text: "We have budget-friendly packages for one-month campaigns. To give you a more precise quote, could you share your target audience and any specific demographics you'd like to reach? ",
        time: "02:18 PM",
        date: "02.09.2023",
      },
    ],
  },
  {
    id: 1,
    name: "Vincent Gilmor",
    avatar: avatar.src,
    title: "Parking place for sale in a new underground parking",
    cover: cover1.src,
    link: "/",
    statusOnline: false,
    timeOnline: "2:58 P.M",
    dateOnline: "01.09.2023",
    messages: [
      {
        userIsSender: true,
        text: "I'm also curious about the pricing for these banner ads",
        time: "11:28 AM",
        date: "02.09.2023",
      },
      {
        userIsSender: true,
        text: "I have a moderate budget, and I'm looking to run the campaign for one month. 🤔",
        time: "11:30 AM",
        date: "02.09.2023",
      },
      {
        userIsSender: false,
        text: "Great! 👍",
        time: "12:38 PM",
        date: "02.09.2023",
      },
      {
        userIsSender: false,
        text: "We have budget-friendly packages for one-month campaigns. To give you a more precise quote, could you share your target audience and any specific demographics you'd like to reach? ",
        time: "02:18 PM",
        date: "02.09.2023",
      },
    ],
  },
  {
    id: 2,
    name: "Karin Suchinda",
    avatar: avatar.src,
    title: "Luxurious apartment on the 5th floor",
    cover: cover1.src,
    link: "/",
    statusOnline: false,
    timeOnline: "2:58 P.M",
    dateOnline: "01.09.2023",
    messages: [
      {
        userIsSender: true,
        text: "If you need more options, then tell us we have a lot of offers",
        time: "11:28 AM",
        date: "12.06.2023",
      },
      {
        userIsSender: true,
        text: "It is also possible to meet on site at our office and discuss. 😉",
        time: "11:30 AM",
        date: "12.06.2023",
      },
      {
        userIsSender: false,
        text: "Great! 👍",
        time: "12:38 PM",
        date: "12.06.2023",
      },
      {
        userIsSender: false,
        text: "We have budget-friendly packages for one-month campaigns. To give you a more precise quote, could you share your target audience and any specific demographics you'd like to reach? ",
        time: "02:18 PM",
        date: "12.06.2023",
      },
    ],
  },
];
