const general = {
  headerDescription: "บริการโฆษณาส่วนตัว",
  help: "ช่วยเหลือ",
  advertiseWithUs: "โฆษณากับเรา",
  rules: "กฎ",
  wishTitle: "สิ่งที่อยากได้ของฉัน",
  createButton: "สร้างโฆษณา",
  viewAll: "ดูทั้งหมด",
  cancel: "ยกเลิก",
  back: "กลับ",
  send: "ส่ง",
  hide: "ซ่อน",
  logIn: "เข้าสู่ระบบ",
  donthaveAccount: "คุณยังไม่มีบัญชีใช่ไหม?",
  haveAccount: "คุณมีบัญชีแล้วหรือยัง?",
  signUp: "ลงทะเบียน",
  phone: "โทรศัพท์",
  password: "รหัสผ่าน",
  forgotPassword: "ลืมรหัสผ่าน",
  termsOfUse: "ข้อตกลงการใช้บริการ",
  withTermsOfUse: "ข้อตกลงการใช้บริการ",
  loginAgree: "เมื่อล็อกอินคุณยินยอมตามข้อตกลงของเรา",
  orLogin: "หรือล็อกอินด้วย",
  loginDescription:
    "หากคุณต้องการรับข้อความจากผู้ใช้ (อีเมลของคุณจะเป็นที่เห็นได้เฉพาะสำหรับผู้ส่งเท่านั้นเมื่อคำถามได้รับการตอบ)",
  specifiedNumberWillReceiveSMS: "หมายเลขที่ระบุจะได้รับ SMS เพื่อการให้สิทธิ์",
  bySignUpAgreement: "เมื่อลงทะเบียนคุณยินยอมตามข้อตกลงการใช้บริการของเรา",
  associatedWithEmailOrPhoneNumber:
    "อีเมลหรือหมายเลขโทรศัพท์ที่เกี่ยวข้องกับโปรไฟล์ BBGO ของคุณคือ?",
  enterPhoneOrEmail: "ป้อนหมายเลขโทรศัพท์หรืออีเมล",
  changePassword: "เปลี่ยนรหัสผ่าน",
  confirmNumber: "ยืนยันหมายเลข",
  enterCodeSentTo: "ป้อนรหัสที่ส่งไปที่",
  sendCodeAgain: "ส่งรหัสอีกครั้ง",
  notificationsMustBeEnabled: "การแจ้งเตือนต้องเปิดใช้งาน",
  anotherWayToGetCode: "วิธีอื่น ๆ ในการรับรหัส",
  receiveCodeWithin1to2Minutes:
    "ภายใน 1-2 นาทีคุณจะได้รับข้อความพร้อมรหัสเพื่อยืนยันหมายเลขโทรศัพท์ของคุณ",
  continue: "ดำเนินการต่อ",
  profile: "โปรไฟล์",
  createAccount: "สร้างบัญชี",
  firstName: "ชื่อ",
  lastName: "นามสกุล",
  email: "อีเมล",
  receiveBBGONewsAndPromotions: "รับข้อมูลเกี่ยวกับข่าวสารและโปรโมชั่นของ BBGO",
  bbgoExclusiveOffersAndNotifications:
    "BBGO จะส่งข้อเสนอพิเศษ, ไอเดีย, อีเมลโปรโมชั่นและการแจ้งเตือนผ่านการกด. คุณสามารถเลือกที่จะไม่รับได้ในการตั้งค่าบัญชีหรือในการแจ้งเตือนทางการตลาด",
  home: "หน้าแรก",
  select: "เลือก",
  reset: "รีเซ็ต",
  showOnMap: "แสดงบนแผนที่",
  viewMore: "ดูเพิ่มเติม",
  default: "ค่าเริ่มต้น",
  showMore: "แสดงเพิ่มเติม",
  addNew: "เพิ่มใหม่",
  updated: "อัปเดต",
  ago: "ที่แล้ว",
  years: "ปี",
  year: "ปี",
  months: "เดือน",
  month: "เดือน",
  days: "วัน",
  day: "วัน",
  hours: "ชั่วโมง",
  hour: "ชั่วโมง",
  minutes: "นาที",
  minute: "นาที",
  seconds: "วินาที",
  second: "วินาที",
  edit: "แก้ไข",
  delete: "ลบ",
  create: "สร้าง",
  done: "เสร็จสิ้น",
  search: "ค้นหา",
  from: "จาก",
  online: "ออนไลน์",
  more: "มากกว่า",
  less: "น้อยกว่า",
  shareWith: "แชร์กับ",
  message: "ข้อความ",
  messageSent: "ข้อความของคุณถูกส่งแล้ว",
  myMessages: "ข้อความของฉัน",
  save: "บันทึก",
  deleteAccount: "ลบบัญชี",
  logOut: "ออกจากระบบ",
  selected: "เลือกแล้ว",
  selectAll: "เลือกทั้งหมด",
  yourAdvertisement: "โฆษณาของคุณ",
  addYourBanners: "เพิ่มแบนเนอร์ของคุณ",
  add: "เพิ่ม",
  deactivate: "ปิดใช้งาน",
  active: "ทำงาน",
  view: "ดู",
  ad: "โฆษณา",
  activate: "เปิดใช้งาน",
  empty: "ว่างเปล่า",
  subscribe: "สมัครรับ",
};

export { general };

// import { useTranslation } from "react-i18next";
// const { t } = useTranslation();
// {
//   t(`general.all`)
// }
