const profile = {
  profile: "โปรไฟล์",
  accountSettings: "การตั้งค่าบัญชี",
  myAds: "โฆษณาของฉัน",
  myMessages: "ข้อความของฉัน",
  wallet: "กระเป๋าเงิน",
  reviews: "รีวิว",
  reviewedProducts: "ผลิตภัณฑ์ที่รีวิว",
  notifications: "การแจ้งเตือน",
  settings: "การตั้งค่า",
  personalInfo: "ข้อมูลส่วนบุคคล",
  address: "ที่อยู่",
  security: "ความปลอดภัย",
  firstName: "ชื่อ",
  lastName: "นามสกุล",
  emailAddress: "ที่อยู่อีเมล",
  phone: "โทรศัพท์",
  country: "ประเทศ",
  cityState: "เมือง/รัฐ",
  password: "รหัสผ่าน",
  enterPassword: "ใส่รหัสผ่าน",
  newPassword: "รหัสผ่านใหม่",
  confirmPassword: "ยืนยันรหัสผ่าน",
  confirmDeleteAccount: "คุณแน่ใจหรือว่าต้องการลบบัญชีของคุณ?",
  confirmLogOut: "คุณแน่ใจหรือว่าต้องการออกจากระบบบัญชีของคุณ?",
  myAdsSecond: "โฆษณาของฉัน",
  active: "ทำงาน",
  waiting: "กำลังรอ",
  inactive: "ไม่ทำงาน",
  rejected: "ถูกปฏิเสธ",
  selectAllAds:
    "เลือกทุกๆ โฆษณาที่ต้องการจากรายการเพื่อทำการกระทำเดียวกันกับทุกๆ โฆษณา",

  subscribeToNotifications: "สมัครรับการแจ้งเตือน",
  receiveMessages: "หากคุณต้องการรับข้อความจากผู้ใช้, สมัครรับ",
  areYouSure: "คุณแน่ใจหรือว่าคุณต้องการ",
  deactivate: "ปิดใช้งาน",
  delete: "ลบ",
  ads: "โฆษณา",
  confirmActivateAd: "คุณแน่ใจหรือว่าต้องการเปิดใช้งานโฆษณา?",
  adsRejectedAfterModeration: "โฆษณาที่ถูกปฏิเสธหลังจากการพิจารณาจะปรากฏที่นี่",
  editAndActivate:
    "ขึ้นอยู่กับเหตุผลที่โฆษณาถูกปฏิเสธ คุณยังสามารถแก้ไขและลองเปิดใช้งานอีกครั้งได้",
  banners: "แบนเนอร์",
  uploadBanner: "อัปโหลดแบนเนอร์",
  dragImageOrOpenExplorer: "ลากรูปภาพหรือ <span>เปิดเอ็กซ์พลอเรอร์</span>",
  sizeAndFileType: "ขนาด <100KB และประเภทไฟล์ PNG/GIF/JPEG",
  languageBanner: "ภาษาแบนเนอร์",
  addLink: "เพิ่มลิงก์",
  yourBanners: "แบนเนอร์ของคุณ",
  fileName: "ชื่อไฟล์",
  size: "ขนาด",
  dataUploaded: "ข้อมูลที่อัปโหลด",
  status: "สถานะ",
  action: "การดำเนินการ",
  approved: "ได้รับการอนุมัติ",
  chooseAll: "เลือกทั้งหมด",
  choosed: "เลือกแล้ว",
  buy: "ซื้อ",
  sell: "ขาย",
  newMessages: "ข้อความใหม่",
  allMessages: "ข้อความทั้งหมด",
  selectMessage: "เลือกข้อความเพื่ออ่าน",
  confirmBlock: "แน่ใจหรือว่าต้องการบล็อกผู้ใช้?",
  block: "บล็อก",
  deleteChat: "ลบแชท",
  deleteChatWith: "คุณต้องการลบแชทกับ",
  goToAd: "ไปที่โฆษณา",
  you: "คุณ",
};

export { profile };

// import { useTranslation } from "react-i18next";
// const { t } = useTranslation();
// {
//   t(`profile.all`)
// }
