const errors = {
  mapErrorNoThailand: "Пожалуйста, выберите место на территории Тайланда",
  enterName: "Введите имя",
  enterPhoneNumber: "Введите номер телефона",
  wrongPhoneNumberFormat: "Неверный формат номера телефона",
  enterCompany: "Введите название компании",
  enterEmail: "Введите адрес электронной почты",
  wrongEmailFormat: "Неверный формат электронной почты",
  enterMessage: "Введите сообщение",
  enterCode: "Введите код",
  wrongCode: "Неверный код",
  enterTitle: "Введите заголовок",
  enterPrice: "Введите цену",
  enterDescription: "Введите описание",
  selectedOption: "Выбран вариант",
  wrongPhoneOrEmailFormat: "Неверный формат телефона/электронной почты",
  enterFirstName: "Введите имя",
  enterLastName: "Введите фамилию",
  enterTheme: "Введите тему",
  selectedFile: "Выбран файл",
  invalidLinkFormat: "Неверный формат ссылки",
  linkIsRequired: "Требуется ссылка",
  fileTooBig1MB: "Файл слишком большой. Перетащите файл размером менее 1 МБ.",
  cannotAddMoreThan6Files: "Вы не можете добавить более 6 файлов.",
  fileTooBig20MB: "Файл слишком большой. Перетащите файл размером менее 20 МБ.",
  fileTooBig10MB: "Файл слишком большой. Перетащите файл размером менее 10 МБ.",
  enterPassword: "Введите пароль",
  addressNotFound: "Адрес не найден",
  selectNoMoreThan10Files: "Вы можете выбрать не более 10 файлов.",
  fileTooBig: "Файл слишком большой.",
  pageNotFound: "Упс!! Страница не найдена",
  pageNotFoundMessage:
    "Страница, которую вы ищете, нигде не найдена. Но не волнуйтесь, мы можем помочь вам вернуться на путь.",
  backToHome: "Вернуться на главную",
};

export { errors };
