const footer = {
  forBuyers: "Для покупателей",
  securityRecommendations: "Рекомендации по безопасности",
  leaveHelpfulFeedback: "Как оставить полезный отзыв",
  getSupport: "Получить поддержку",
  helpForBuyers: "Помощь для покупателей",
  aboutPaymentAndDelivery: "Об оплате и доставке",
  forSellers: "Для продавцов",
  siteRules: "Правила сайта",
  advertising: "Реклама",
  howToStartSellingOnBBGO: "Как начать продавать на bbgo.com",
  rates: "Тарифы",
  privacyPolicy: "Политика конфиденциальности",
  aboutUs: "О нас",
  aboutBBGO: "О bbgo.com",
  faq: "Часто задаваемые вопросы",
  contactInformation: "Контактная информация",
  contentLegalityProtection: "Защита законности контента",
  partnership: "Партнерство",
  app: "Приложение",
  scanQRCodeToInstallApp: "Scan the QR code to install the mobile app",
  copyrightBBGO: "Авторское право © 2023 BBGO. Все права защищены.",
  reportBug: "Сообщить о ошибке",
};

export { footer };
