const general = {
  headerDescription: "Служба частных обьвлений",
  help: "Помощь",
  advertiseWithUs: "Рекламировать с нами",
  rules: "Правила",
  wishTitle: "Мои избранные",
  createButton: "Добавить обьявление",
  viewAll: "Посмотреть все",
  cancel: "Отмена",
  back: "Назад",
  send: "Отправить",
  hide: "Скрыть",
  logIn: "Войти",
  donthaveAccount: "У вас еще нет аккаунта?",
  haveAccount: "У вас уже есть аккаунт?",
  signUp: "Зарегистрироваться",
  phone: "Телефон",
  password: "Пароль",
  forgotPassword: "Забыли пароль",
  termsOfUse: "Условия предоставления услуг",
  withTermsOfUse: "Условиями предоставления услуг",
  loginAgree: "При входе вы соглашаетесь с нашими",
  orLogin: "Или войти с помощью",
  loginDescription:
    "Если вы хотите получать сообщения от пользователей (ваш электронный адрес будет виден отправителю только в случае ответа на вопрос).",
  specifiedNumberWillReceiveSMS:
    "На указанный номер будет отправлено SMS для авторизации",
  bySignUpAgreement: "При регистрации вы соглашаетесь с нашими",
  associatedWithEmailOrPhoneNumber:
    "Какой адрес электронной почты или номер телефона связан с вашим профилем в BBGO?",
  enterPhoneOrEmail: "Введите номер телефона или адрес электронной почты",
  changePassword: "Изменить пароль",
  confirmNumber: "Подтвердить номер",
  enterCodeSentTo: "Введите код, отправленный на",
  sendCodeAgain: "Отправить код еще раз",
  notificationsMustBeEnabled: "Уведомления должны быть включены",
  anotherWayToGetCode: "Другой способ получить код",
  receiveCodeWithin1to2Minutes:
    "В течение 1-2 минут вы получите сообщение с кодом для подтверждения вашего номера телефона",
  continue: "Продолжить",
  profile: "Профиль",
  createAccount: "Создать аккаунт",
  firstName: "Имя",
  lastName: "Фамилия",
  email: "Электронная почта",
  receiveBBGONewsAndPromotions: "Получать информацию о новостях и акциях BBGO",
  bbgoExclusiveOffersAndNotifications:
    "BBGO отправит вам эксклюзивные предложения, идеи, рекламные электронные письма и уведомления. Вы можете отказаться в настройках своего аккаунта или в маркетинговом уведомлsении.",
  home: "Главная",
  select: "Выбрать",
  reset: "Сбросить",
  showOnMap: "Показать на карте",
  viewMore: "Просмотреть еще",
  default: "По умолчанию",
  showMore: "Показать больше",
  addNew: "",
  updated: "Обновлено",
  ago: "назад",
  years: "лет",
  year: "год",
  months: "месяцев",
  month: "месяц",
  days: "дней",
  day: "день",
  hours: "часов",
  hour: "час",
  minutes: "минут",
  minute: "минута",
  seconds: "секунд",
  second: "секунда",
  edit: "Редактировать",
  delete: "Удалить",
  create: "Создать",
  done: "Готово",
  search: "Поиск",
  from: "От",
  online: "Онлайн",
  more: "Больше",
  less: "Меньше",
  shareWith: "Поделиться с",
  message: "Сообщение",
  messageSent: "Ваше сообщение отправлено",
  myMessages: "Мои сообщения",
  save: "Сохранить",
  deleteAccount: "Удалить аккаунт",
  logOut: "Выйти",
  selected: "Выбрано",
  selectAll: "Выбрать все",
  yourAdvertisement: "Ваше объявление",
  addYourBanners: "Добавьте свои баннеры",
  add: "Добавить",
  deactivate: "Деактивировать",
  active: "Активные",
  view: "Просмотр",
  ad: "объявление",
  activate: "Активировать",
  empty: "Пусто",
  subscribe: "Подписаться",
};

export { general };
