const profile = {
  profile: "Профиль",
  accountSettings: "Настройки аккаунта",
  myAds: "Мои объявления",
  myMessages: "Мои сообщения",
  wallet: "Кошелек",
  reviews: "Отзывы",
  reviewedProducts: "Отзывы о товарах",
  notifications: "Уведомления",
  settings: "Настройки",
  personalInfo: "Личная информация",
  address: "Адрес",
  security: "Безопасность",
  firstName: "Имя",
  lastName: "Фамилия",
  emailAddress: "Адрес электронной почты",
  phone: "Телефон",
  country: "Страна",
  cityState: "Город/Область",
  password: "Пароль",
  enterPassword: "Введите пароль",
  newPassword: "Новый пароль",
  confirmPassword: "Подтвердите пароль",
  confirmDeleteAccount: "Вы уверены, что хотите удалить свой аккаунт?",
  confirmLogOut: "Вы уверены, что хотите выйти из своего аккаунта?",
  myAdsSecond: "Мои объявления",
  active: "Активные",
  waiting: "Ожидающие",
  inactive: "Неактивные",
  rejected: "Отклоненные",
  selectAllAds:
    "Выберите все необходимые объявления из списка, чтобы применить к ним одинаковые действия",

  subscribeToNotifications: "Подписаться на уведомления",
  receiveMessages:
    "Если вы хотите получать сообщения от пользователей, подпишитесь",
  areYouSure: "Вы уверены, что хотите",
  deactivate: "деактивировать",
  delete: "удалить",
  ads: "объявления",
  confirmActivateAd: "Вы уверены, что хотите активировать объявление?",
  adsRejectedAfterModeration:
    "Объявления, отклоненные после модерации, отображаются здесь.",
  editAndActivate:
    "В зависимости от причины отклонения, вы все равно можете отредактировать его и попробовать активировать снова.",
  banners: "Баннеры",
  uploadBanner: "Загрузить баннер",
  dragImageOrOpenExplorer:
    "Перетащите изображение или <span>Открыть проводник</span>",
  sizeAndFileType: "Размер <100KB и тип файла PNG/GIF/JPEG",
  languageBanner: "Язык баннера",
  addLink: "Добавить ссылку",
  yourBanners: "Ваши баннеры",
  fileName: "Имя файла",
  size: "Размер",
  dataUploaded: "Данные загружены",
  status: "Статус",
  action: "Действие",
  approved: "Утверждено",
  chooseAll: "Выбрать все",
  choosed: "Выбрано",
  buy: "Купить",
  sell: "Продавать",
  newMessages: "Новые сообщения",
  allMessages: "Все сообщения",
  selectMessage: "Выберите сообщение для прочтения",
  confirmBlock: "Вы уверены, что хотите заблокировать пользователя?",
  block: "Заблокировать",
  deleteChat: "Удалить чат",
  deleteChatWith: "Вы хотите удалить чат с",
  goToAd: "Перейти к объявлению",
  you: "Вы",
  noCardAdded: "У вас пока нет добавленной карты",
  addCardPrompt: "Добавьте карту, чтобы использовать платные услуги BBGO",
  addCard: "Добавить карту",
  mainCard: "Основная карта",
  makeMainCard: "Сделать основной",
  removeCardWarning:
    "Карта будет удалена из вашего кошелька и личного аккаунта",
  deleteCard: "Удалить карту",
  successful: "Успешно!",
  cardSuccessfullyAdded: "Карта успешно добавлена",
  cardNumber: "Номер карты",
  cvv: "CVV",
  validity: "Срок действия",
  mmYY: "ММ/ГГ",
  bad: "Плохо",
  badReviews: "Этот автор получил много плохих отзывов",
  acceptable: "Приемлемо",
  acceptableReviews: "Этот автор получил много приемлемых отзывов",
  normal: "Нормально",
  normalReviews: "Этот автор получил много нормальных отзывов",
  good: "Хорошо",
  goodReviews: "Этот автор получил много хороших отзывов",
  excellent: "Отлично",
  excellentReviews: "Этот автор получил много отличных отзывов",
  yourReviews: "Ваши отзывы",
  confirmDeleteReviewedProducts:
    "Вы уверены, что хотите удалить отзывы о продуктах?",
  confirmDeleteNotifications: "Вы уверены, что хотите удалить уведомления?",
};

export { profile };
